{{- with .Values }}
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Release.Name }}-react-docker
  spec:
    replicas: {{ .reactDocker.replicaCount }}
    selector:
      matchLabels:
        app: {{ .Release.Name }}-react-docker
    template:
      metadata:
        labels:
          app: {{ .Release.Name }}-react-docker
      spec:
        containers:
        - name: react-docker
          image: {{ .reactDocker.image }}
          ports:
          - containerPort: 80

- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Release.Name }}-load-balancer
  labels:
    app: {{ .Release.Name }}-react-docker
  spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    selector:
      app: {{ .Release.Name }}-react-docker

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Release.Name }}-mysql-deployment
  spec:
    replicas: {{ .mysql.replicaCount }}
    selector:
      matchLabels:
        app: mysql
    template:
      metadata:
        labels:
          app: mysql
      spec:
        containers:
        - name: mysql
          image: {{ .mysql.image }}
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .mysql.rootPassword }}
          - name: MYSQL_DATABASE
            value: {{ .mysql.database }}

- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Release.Name }}-mysql-service
  spec:
    selector:
      app: mysql
    ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Release.Name }}-node-deployment
  spec:
    replicas: {{ .node.replicaCount }}
    selector:
      matchLabels:
        app: node
    template:
      metadata:
        labels:
          app: node
      spec:
        containers:
        - name: node
          image: {{ .node.image }}
          ports:
            - containerPort: 3001

- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Release.Name }}-node
  spec:
    selector:
      app: node
    ports:
    - port: 80
      targetPort: 3001
{{- end }}
