apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.servicePort}}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
    nodePort: {{ .Values.nodeProt }}
  selector:
    app: {{ .Values.appName }}